version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - lll
    - paralleltest
    - testpackage
    - wsl
  settings:
    goheader:
      template: |-
        Copyright 2023 Clastix Labs
        SPDX-License-Identifier: Apache-2.0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/clastix/cluster-api-control-plane-provider-kamaji)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
