name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    name: tag release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          draft: true
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          files: |
            config/control-plane-components.yaml
            config/metadata.yaml
